title: The inuit-rails Manual

markdown: kramdown

collections:
  lessons:
    output: true
    permalink: /lessons/:slug

defaults:
  -
    scope:
      path: ""
      type: "lessons"
    values:
      layout: lesson
