title: The We Got Coders inuit-rails Manual
email: hello@wegotcoders.com
description: >
  A walk through guide for getting started with the basic features of the
  wegotcoders inuit-rails gem
twitter_username: wegotcoders
github_username:  wegotcoders

# Build settings
markdown: kramdown
