# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: inuit-rails 0.2.8 ruby lib

Gem::Specification.new do |s|
  s.name = "inuit-rails"
  s.version = "0.2.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Dan Garland"]
  s.date = "2014-10-04"
  s.description = "A Rails enginge that permits the use of inuit css files within a Rails application. "
  s.email = "dan@dangarland.co.uk"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".bowerrc",
    ".document",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bower.json",
    "inuit-rails.gemspec",
    "lib/inuit-rails.rb",
    "lib/inuit-rails/rails.rb",
    "lib/inuit-rails/rails/engine.rb",
    "lib/inuit-rails/rails/version.rb",
    "vendor/stylesheets/inuit-box-sizing/_generic.box-sizing.scss",
    "vendor/stylesheets/inuit-defaults/_settings.defaults.scss",
    "vendor/stylesheets/inuit-functions/_tools.functions.scss",
    "vendor/stylesheets/inuit-mixins/_tools.mixins.scss",
    "vendor/stylesheets/inuit-normalize/_generic.normalize.scss",
    "vendor/stylesheets/inuit-page/_base.page.scss",
    "vendor/stylesheets/inuit.scss"
  ]
  s.homepage = "http://github.com/dmgarland/inuit-rails"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "The Inuit CSS framework packaged as a Rails/Sprockets compatible gem"
end

