# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: inuit-rails 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "inuit-rails"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Dan Garland"]
  s.date = "2014-10-04"
  s.description = "A Rails enginge that permits the use of inuit css files within a Rails application. "
  s.email = "dan@dangarland.co.uk"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/inuit-rails.rb"
  ]
  s.homepage = "http://github.com/dmgarland/inuit-rails"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "The Inuit CSS framework packaged as a Rails/Sprockets compatible gem"
end

